routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::namespace('Admin\\')
    ->group(function (){
        Route::get('/', 'PostulacionesController@registrar')->name('postulantes.llamados');
        Route::get('/registro/{llamado}', 'PostulacionesController@carreras')
            ->where('llamado','\d')
            ->name('postulantes.carreras');
        Route::post('/registro', 'PostulacionesController@guardar')->name('postulantes.guardar');
        Route::get('registro/{uuid}/comprobante', 'PostulacionesController@constancia')
            ->where('uuid', '[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?4[0-9a-fA-F]{3}-?[89abAB][0-9a-fA-F]{3}-?[0-9a-fA-F]{12}')
            ->name('postulantes.constancia');
        Route::get('registro/{uuid}/imprimir', 'PostulacionesController@imprimir')
            ->where('uuid', '[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?4[0-9a-fA-F]{3}-?[89abAB][0-9a-fA-F]{3}-?[0-9a-fA-F]{12}')
            ->name('postulantes.imprimir');
        Route::get('/registro/manuales', 'PostulacionesController@getManuales')->name('postulantes.manuales');
    });


Route::middleware('auth')
    ->namespace('Admin\\')
    ->group(function (){

        //USUARIOS
        Route::get('/usuarios', 'UsuariosController@listado')->name('usuarios.listado');
        Route::post('/usuarios','UsuariosController@crear')->name('usuarios.crear');
        Route::delete('/usuarios/{user}', 'UsuariosController@eliminar')->name('usuarios.eliminar');
        Route::get('/usuarios/{user}/editar', 'UsuariosController@editar')->name('usuarios.editar');
        Route::put('/usuarios/{user}', 'UsuariosController@actualizar')->name('usuarios.actualizar');
        Route::get('/usuarios/getUsuariosJson', 'UsuariosController@getUsuariosJson')->name('usuarios.getjson');
        Route::get('/usuarios/manuales', 'UsuariosController@getManuales')->name('usuarios.manuales');

        //CARRERAS
        Route::get('carreras', 'CarrerasController@listado')->name('carreras.listado');
        Route::get('carreras/{carrera}', 'CarrerasController@ver')
            ->where('carrera','\d')
            ->name('carreras.ver');
        Route::get('carreras/nueva', 'CarrerasController@crear')->name('carreras.crear');
        Route::post('carreras', 'CarrerasController@guardar')->name('carreras.guardar');
        Route::get('carreras/{carrera}/editar', 'CarrerasController@editar')->name('carreras.editar');
        Route::put('carreras/{carrera}', 'CarrerasController@actualizar')->name('carreras.actualizar');
        Route::delete('carreras/{carrera}', 'CarrerasController@eliminar')->name('carreras.eliminar');

        // ASIGNATURAS
        Route::get('asignaturas', 'AsignaturasController@listado')->name('asignaturas.listado');
        Route::get('asignaturas/nueva', 'AsignaturasController@crear')->name('asignaturas.crear');
        Route::post('asignaturas', 'AsignaturasController@guardar')->name('asignaturas.guardar');
        Route::get('asignaturas/{asignatura}/editar', 'AsignaturasController@editar')->name('asignaturas.editar');
        Route::put('asignaturas/{asignatura}', 'AsignaturasController@actualizar')->name('asignaturas.actualizar');
        Route::delete('asignaturas/{asignatura}', 'AsignaturasController@eliminar')->name('asignaturas.eliminar');

        // LLAMADOS
        Route::get('llamados', 'LlamadosController@listado')->name('llamados.listado');
        Route::get('llamados/nuevo', 'LlamadosController@crear')->name('llamados.crear');
        Route::get('llamados/{llamado}', 'LlamadosController@ver')->name('llamados.ver');
        Route::post('llamados', 'LlamadosController@guardar')->name('llamados.guardar');
        Route::get('llamados/{llamado}/editar', 'LlamadosController@editar')->name('llamados.editar');
        Route::get('llamados/{llamado}/editar-tribunal', 'LlamadosController@editarTribunal')->name('llamados.editarTribunal');
        Route::put('llamados/{llamado}', 'LlamadosController@actualizar')->name('llamados.actualizar');
        Route::put('llamados/{llamado}/actualizar-tribunal', 'LlamadosController@actualizarTribunal')->name('llamados.actualizarTribunal');
        Route::delete('llamados/{llamado}', 'LlamadosController@eliminar')->name('llamados.eliminar');
        Route::get('llamados/getLlamadoJson', 'LlamadosController@getLlamadoJson')->name('llamados.getjson');

        //EVALUADORES
        Route::get('evaluadores', 'EvaluadoresController@listado')->name('evaluadores.listado');
        Route::get('evaluadores/{evaluador}', 'EvaluadoresController@ver')->name('evaluadores.ver');
        Route::post('evaluadores', 'EvaluadoresController@guardar')->name('evaluadores.guardar');
        Route::put('evaluadores/{evaluador}', 'EvaluadoresController@actualizar')->name('evaluadores.actualizar');
        Route::delete('evaluadores/{evaluador}', 'EvaluadoresController@eliminar')->name('evaluadores.eliminar');

        // TRIBUNAL
        Route::get('tribunal/crear', 'TribunalesController@crear')->name('tribunales.crear');
        Route::get('tribunal/getCarreras/{id}', 'TribunalesController@getCarreras')->name('tribunales.getCarreras');
        Route::post('tribunal', 'TribunalesController@guardar')->name('tribunales.guardar');

        //POSTULANTES
        Route::get('postulaciones', 'PostulacionesController@listado')->name('postulaciones.listado');
        Route::get('postulaciones/{postulacion}/', 'PostulacionesController@ver')->name('postulaciones.ver');
        Route::get('postulaciones/curriculum/{cv}', 'PostulacionesController@getCv')->name('postulaciones.getCv');
        Route::get('postulaciones/curriculum/{cv}/descargar', 'PostulacionesController@descargarCv')->name('postulaciones.descargarCv');
        Route::get('postulaciones/{postulacion}/asignatura/{asignatura}/evaluar', 'PostulacionesController@evaluar')->name('postulaciones.evaluar');
        Route::put('postulaciones/{asignatura_postulacion}', 'PostulacionesController@guardarPuntaje')->name('postulaciones.guardarPuntaje');
        Route::post('postulaciones/editando/{asignatura_postulacion}/', 'PostulacionesController@editando')->name('postulaciones.editando');


        //INFORMES
        Route::get('informes/{llamado}/pdf', 'InformesController@listado')->name('informes.listado');
        Route::post('informes/{llamado}/pdf', 'InformesController@generarPdf')->name('informes.generarPdf');
        Route::get('informes/{llamado}/xls', 'InformesController@listadoExcel')->name('informes.listadoExcel');
        Route::post('informes/{llamado}/xls', 'InformesController@generarExcel')->name('informes.generarExcel');


        //TABLA
//        Route::get('tabla', 'TablaPonderacionController@listado')->name('tabla.listado');
//        Route::post('tabla', 'TablaPonderacionController@guardar')->name('tabla.guardar');
//        Route::get('/tabla/{tabla}/editar', 'TablaPonderacionController@editar')->name('tabla.editar');
//        Route::put('/tabla/{tabla}', 'TablaPonderacionController@actualizar')->name('tabla.actualizar');
//        Route::delete('/tabla/{tabla}', 'TablaPonderacionController@eliminar')->name('tabla.eliminar');
//        Route::get('/tabla/{tabla}', 'TablaPonderacionController@agregarSubitem')->name('tabla.agregarSubitem');
    });


Auth::routes();

app/Postulante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Postulante extends Model
{
    use Notifiable;

    protected $guarded = [];

    public function uploads()
    {
        return $this->morphToMany(Upload::class, 'uploadable');
    }

    public function llamados()
    {
        return $this->belongsToMany(Llamado::class, 'postulaciones');
    }

    public function postulaciones()
    {
        return $this->hasMany(Postulacion::class, 'postulante_id');
    }

    public function asignatura_postulacion()
    {
        return $this->hasManyThrough(AsignaturaPostulacion::class, Postulacion::class);
    }

    public function getFullNameAttribute()
    {
        return ucwords(strtolower($this->apellido . " " . $this->nombre));
    }
    public function getFileNameSlugAttribute()
    {
        return Str::slug($this->full_name);
    }

    public function getTitulosAttribute()
    {
        return json_decode($this->titulos_grado);
    }

    public function getFilePath()
    {
        return 'cvs/';
    }

    public function getStorageFilePath()
    {
        return 'cvs/';
    }

    public function esta_inscripto($llamado_id)
    {
        return $this->llamados()->where("llamados.id",$llamado_id)->first();
    }

    public function getPuntaje($llamado_id, $asignatura_id)
    {
//        return DB::table('postulaciones as pst')
//            ->select('pst.id as postulacion_id', DB::raw("CONCAT(pos.apellido, ' ', pos.nombre) as nombre"),
//                'tp.id as ponderacion_id', DB::raw("SUM(atp.puntaje) as puntaje"), 'pos.id as postulante_id')
//            ->join('asignatura_postulacion as ap', 'pst.id', '=', 'ap.postulacion_id')
//            ->join('asignatura_tabla_puntajes as atp', 'ap.id', '=', 'atp.asignatura_postulacion_id')
//            ->join('tabla_ponderacion as tp', 'atp.tabla_ponderacion_id', '=', 'tp.id')
//            ->join('postulantes as pos', 'pst.postulante_id', '=', 'pos.id')
//            ->where('pst.llamado_id', $llamado_id)
//            ->where('ap.asignatura_id', $asignatura_id)
//            ->groupBy('pst.id','tp.id')
//            ->get();

        return $this->postulaciones()->where('llamado_id', $llamado_id)->first()
            ->asignaturas_postulaciones->where('asignatura_id', $asignatura_id)->first();
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\ResetPassword;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Authenticatable implements CanResetPassword
{
    use Notifiable, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'username','apellido','email', 'password', 'estado'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tribunales()
    {
        return $this->hasMany(Tribunal::class);
    }

    public function llamados()
    {
        return $this->belongsToMany(Llamado::class,'tribunales');
    }
    //SCOPES
    public function scopeBuscarUsuario($query, Request $request)
    {
        if ($request->has('buscar') && !is_null($request->get('buscar'))){
            $query->where('nombre', 'LIKE', "%{$request->get('buscar')}%")
                ->orWhere('apellido', 'LIKE', "%{$request->get('buscar')}%");
        }
        return $query;
    }

    // FIN SCOPES

    // ACCESOR Y MUTATORS
    public function getFullNameAttribute()
    {
        return "{$this->apellido} {$this->nombre}";
    }

    // FIN ACCESOR Y MUTATORS

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token, $this->email));
    }
}

resources/views/admin/postulaciones/listado.blade.php
@extends('layouts.master')
@section('titulo', 'Listado de postulaciones')
@section('contenido')

    @include('partials.errors')
    @include('partials.success')
    <form action="{{ route('postulaciones.listado') }}" method="GET" id="buscarPostulanteForm">

        <div class="row" style="margin-bottom: 1%">
            <div class="col-md-2">
                <p class="text-danger"><b>Cantidad de resultados: {{ $cantidad_inscriptos }}</b></p>
            </div>

            <div class="col-md-2 offset-3">
                <select name="llamado" id="llamado" class="form-control">
                    <option selected disabled>Seleccionar el llamado</option>
                    <option value="todos">Todos</option>
                    @foreach($llamados as $llamado)
                        <option value="{{ $llamado->id }}" @if(request('llamado') == $llamado->id) selected @endif>{{ $llamado->titulo }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" value="{{ request('postulante') }}" name="postulante" id="buscarPostulante" placeholder="Buscar postulante">
            </div>

            <div class="col-md-2">
                <span class="cursor" title="Buscar" id="buscar" style="color:#3c62d1">
                    <i class="fas fa-search fa-2x"></i>
                </span>
                <a href="{{ route('postulaciones.listado') }}" title="Limpiar resultados" style="color:red">
                    <i class="fas fa-broom fa-2x"></i>
                </a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-dark">
            <th>#</th>
            <th>Postulante</th>
            <th>Llamado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
            @forelse($postulaciones as $postulacion)
                <tr>
                    <td>{{ $postulacion->id }}</td>
                    <td>{{ $postulacion->postulante->full_name }}</td>
                    <td>{{ $postulacion->llamado->titulo }}</td>
                    <td>
                        <a href="{{ route('postulaciones.ver', $postulacion) }}" class="btn btn-primary btn-circle btn-sm" title="Detalle">
                            <i class="fas fa-eye"></i>
                        </a>

                    </td>
                </tr>
            @empty
                <td colspan="5">No se encontraron resultados</td>
            @endforelse
            </tbody>
        </table>


        {{ $postulaciones->appends([
            'llamado' => request('llamado'),
            'buscar' => request('postulante')
        ])->links() }}
    </div>
@endsection
@section('js')
    <script>
        $(function () {

            $("#llamado").change(function (){
                if ($(this).val() == 'todos'){
                    window.location.href = "{{ route('postulaciones.listado') }}";
                    return;
                }
                $("#buscarPostulanteForm").submit();
            });

            $("#buscarPostulante").keyup(function(e){
                if(e.keyCode == 13){
                    if ($(this).val() != ''){
                        $("#buscarPostulanteForm").submit();
                    } else{
                        alert("Debe ingresar un parametro de busqueda");
                    }

                }
            });

            $("#buscar").click(function () {
                $("#buscarPostulanteForm").submit();
            });

        });
    </script>
@endsection

resources/views/admin/postulaciones/tabla.blade.php
@extends('layouts.master')
@section('titulo', "Tabla de ponderacion para carga de puntaje")
@section('contenido')

    @include('partials.errors')
    @include('partials.success')

    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Postulante</h6>
                </div>
                <div class="card-body">
                    <div class="modal-body">
                        <div class="form-row">
                            <div class="col">
                                <label class="font-weight-bold">Apellido y Nombre</label>
                                <p>{{ $postulacion->postulante->full_name }}</p>
                            </div>

                            <div class="col">
                                <label class="font-weight-bold">DNI</label>
                                <p>{{ $postulacion->postulante->dni }}</p>
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label class="font-weight-bold">Correo electrónico</label>
                                <p>{{ $postulacion->postulante->email }}</p>
                            </div>

                            <div class="col">
                                <label class="font-weight-bold">Teléfono</label>
                                <p>{{ $postulacion->postulante->telefono }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Títulos de grado</h6>
                </div>
                <div class="card-body">
                    <div class="modal-body">
                        <ul>
                            @foreach($postulacion->postulante->titulos as $titulo)
                                <li>{{ $titulo }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <form action="{{ route('postulaciones.guardarPuntaje', $asignatura_postulacion) }}"  id="formPuntajes" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">{{ $asignatura->nombre }}</h6>
                    </div>
                    <div class="card-body">
                        <div class="modal-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                @foreach($tabla_ponderacion as $item)
                                    <li class="nav-item">
                                        <a class="nav-link @if ($loop->first) active @endif" id="tab-{{ $item->id }}" data-toggle="tab" href="#{{ $item->letra . "_" . $asignatura->id }}" role="tab" aria-controls="tab{{ $item->id }}" aria-selected="true">{{ $item->nombre }}</a>
                                    </li>
                                @endforeach
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                @foreach($tabla_ponderacion as $item)
                                    <div class="tab-pane fade show @if ($loop->first) active @endif" id="{{ $item->letra . "_" . $asignatura->id }}" role="tabpanel" aria-labelledby="tab-{{ $item->id }}">
                                        <table class="table table-sm table-bordered">
                                            <thead>
                                            <tr>
                                                <th>Código</th>
                                                <th>Descripción</th>
                                                <th>Punjaje máximo</th>
                                                <th>Puntaje otorgado</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($item->items as $nro => $subItem)
                                                @php $puntuacion = $subItem->asignatura_postulacion()->where('asignatura_postulacion_id', $asignatura_postulacion->id)->first() @endphp
                                                <tr @if( $subItem->hijos->count()) style="font-weight: bold; color:black; background: #f2f2f2"@endif
                                                @if( $subItem->padre ) style="background: #f2f2f2"@endif>
                                                    <td>{{ $subItem->codigo_item }}</td>
                                                    <td>{!! $subItem->nombre_item !!}</td>
                                                    <td>
                                                        {{ $subItem->puntaje_maximo }}
                                                    </td>
                                                    @if( !$subItem->hijos->count())
                                                        <td>
                                                            <input type="number" class="form-control
                                                                @if(empty($subItem->codigo_item)) {{ $subItem->padre->codigo_item."_".$subItem->tipo }} @endif"
                                                                min="{{ $subItem->puntaje_minimo }}" max="{{ $subItem->puntaje_maximo }}" value="{{ $puntuacion->pivot->puntaje ?? '' }}"
                                                                   name="asig_post[{{ $asignatura_postulacion->id }}][subitem][{{ $subItem->id }}]" placeholder="0">
                                                        </td>
                                                    @else
                                                        <td></td>
                                                    @endif
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="mx-auto">
                <button class="btn btn-success btn-lg" type="submit" id="guardar">Guardar</button>
            </div>
        </div>
    </form>
@endsection
@section('js')
    <script>
        $(function () {
            $('input[type=number]').on('wheel', function(e){
                return false;
            });

            // $(".A10_unico").keyup(function () {
            //     if($.trim($(this).val()) == ''){
            //         $(".A10_unico").prop('disabled', false);
            //     }else{
            //         $(".A10_unico").not(this).prop('disabled', true);
            //     }
            // });

            $("input[type=number]").focusout(function(){
                var min = parseInt($(this).attr("min"));
                var max = parseInt($(this).attr("max"));
                var puntaje = parseInt($(this).val());

                if (puntaje < min){
                    alert("El puntaje no puede ser menor a "+min);
                    $(this).val(min);
                    $(this).addClass("is-invalid");
                    $(this).focus();
                }

                if (puntaje > max){
                    alert("El puntaje no puede ser mayor a "+max);
                    $(this).addClass("is-invalid");
                    $(this).val(max);
                    $(this).focus();
                }

                $(this).removeClass("is-invalid").addClass("is-valid");
                return;
            });

            var url = "{{ route('postulaciones.editando', $asignatura_postulacion->id) }}";

            var callback = function() {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': "{{ csrf_token() }}"
                    }
                });

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        editando: moment().format("YYYY-MM-DD HH:mm:ss")
                    },
                });
            };

            setInterval(callback, 60000);

            $("form").submit(function(){
                $(this).find(':input').filter(function() { return !this.value; }).attr('disabled', 'disabled');
                return true;
            });

            $(window).keydown(function(event){
                if(event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
    </script>
@endsection

resources/views/admin/postulaciones/ver.blade.php
@extends('layouts.master')
@section('titulo', 'Ver postulante')
@section('contenido')

    @include('partials.errors')
    @include('partials.success')
    <style>
        .pdfobject-container { height: 80rem; border: 1rem solid rgba(0,0,0,.1); }

    </style>
    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Postulante</h6>
                </div>
                <div class="card-body">
                    <div class="modal-body">
                        <div class="form-row">
                            <div class="col">
                                <label class="font-weight-bold">Apellido y Nombre</label>
                                <p>{{ $postulacion->postulante->full_name }}</p>
                            </div>

                            <div class="col">
                                <label class="font-weight-bold">DNI</label>
                                <p>{{ $postulacion->postulante->dni }}</p>
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="col">
                                <label class="font-weight-bold">Correo electrónico</label>
                                <p>{{ $postulacion->postulante->email }}</p>
                            </div>

                            <div class="col">
                                <label class="font-weight-bold">Teléfono</label>
                                <p>{{ $postulacion->postulante->telefono }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Títulos de grado</h6>
                </div>
                <div class="card-body">
                    <div class="modal-body">
                        <ul>
                            @foreach($postulacion->postulante->titulos as $titulo)
                                <li>{{ $titulo }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h3 class="h4 mb-0 text-gray-800">Asignaturas en las que se postuló</h3>
    </div>

    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="table-dark">
                <tr class="text-center">
                    <th>Asignatura</th>
                    <th>Evaluar</th>
                </tr>
                </thead>
                <tbody>
                @foreach($asignaturas as $asignatura)
                    <tr>
                        <td>{{ $asignatura->nombre }}</td>
                        <td class="text-center">
                            <a href="{{ route('postulaciones.evaluar', [$postulacion, $asignatura]) }}" class="btn btn-sm btn-danger btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-user-check"></i>
                            </span>
                                <span class="text">Evaluar</span>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12 mx-auto">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Curriculum vitae</h6>
                    <div class="dropdown no-arrow">
                        <a href="{{ route('postulaciones.descargarCv', $postulacion->upload) }}" class="btn btn-success btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-download"></i>
                            </span>
                            <span class="text">Descargar</span>
                        </a>

                    </div>
                </div>
                <div class="card-body">
                    <div class="modal-body">
                        <div id="cv">
                            <embed src="{{ action('Admin\PostulacionesController@getCv', ['cv'=> $postulacion->upload->id]) }}"
                                   type="application/pdf" width="100%" height="700rem">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection