routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::namespace('Admin\\')
    ->group(function (){
        Route::get('/', 'PostulacionesController@registrar')->name('postulantes.llamados');
        Route::get('/registro/{llamado}', 'PostulacionesController@carreras')
            ->where('llamado','\d')
            ->name('postulantes.carreras');
        Route::post('/registro', 'PostulacionesController@guardar')->name('postulantes.guardar');
        Route::get('registro/{uuid}/comprobante', 'PostulacionesController@constancia')
            ->where('uuid', '[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?4[0-9a-fA-F]{3}-?[89abAB][0-9a-fA-F]{3}-?[0-9a-fA-F]{12}')
            ->name('postulantes.constancia');
        Route::get('registro/{uuid}/imprimir', 'PostulacionesController@imprimir')
            ->where('uuid', '[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?4[0-9a-fA-F]{3}-?[89abAB][0-9a-fA-F]{3}-?[0-9a-fA-F]{12}')
            ->name('postulantes.imprimir');
        Route::get('/registro/manuales', 'PostulacionesController@getManuales')->name('postulantes.manuales');
    });


Route::middleware('auth')
    ->namespace('Admin\\')
    ->group(function (){

        //USUARIOS
        Route::get('/usuarios', 'UsuariosController@listado')->name('usuarios.listado');
        Route::post('/usuarios','UsuariosController@crear')->name('usuarios.crear');
        Route::delete('/usuarios/{user}', 'UsuariosController@eliminar')->name('usuarios.eliminar');
        Route::get('/usuarios/{user}/editar', 'UsuariosController@editar')->name('usuarios.editar');
        Route::put('/usuarios/{user}', 'UsuariosController@actualizar')->name('usuarios.actualizar');
        Route::get('/usuarios/getUsuariosJson', 'UsuariosController@getUsuariosJson')->name('usuarios.getjson');
        Route::get('/usuarios/manuales', 'UsuariosController@getManuales')->name('usuarios.manuales');

        //CARRERAS
        Route::get('carreras', 'CarrerasController@listado')->name('carreras.listado');
        Route::get('carreras/{carrera}', 'CarrerasController@ver')
            ->where('carrera','\d')
            ->name('carreras.ver');
        Route::get('carreras/nueva', 'CarrerasController@crear')->name('carreras.crear');
        Route::post('carreras', 'CarrerasController@guardar')->name('carreras.guardar');
        Route::get('carreras/{carrera}/editar', 'CarrerasController@editar')->name('carreras.editar');
        Route::put('carreras/{carrera}', 'CarrerasController@actualizar')->name('carreras.actualizar');
        Route::delete('carreras/{carrera}', 'CarrerasController@eliminar')->name('carreras.eliminar');

        // ASIGNATURAS
        Route::get('asignaturas', 'AsignaturasController@listado')->name('asignaturas.listado');
        Route::get('asignaturas/nueva', 'AsignaturasController@crear')->name('asignaturas.crear');
        Route::post('asignaturas', 'AsignaturasController@guardar')->name('asignaturas.guardar');
        Route::get('asignaturas/{asignatura}/editar', 'AsignaturasController@editar')->name('asignaturas.editar');
        Route::put('asignaturas/{asignatura}', 'AsignaturasController@actualizar')->name('asignaturas.actualizar');
        Route::delete('asignaturas/{asignatura}', 'AsignaturasController@eliminar')->name('asignaturas.eliminar');

        // LLAMADOS
        Route::get('llamados', 'LlamadosController@listado')->name('llamados.listado');
        Route::get('llamados/nuevo', 'LlamadosController@crear')->name('llamados.crear');
        Route::get('llamados/{llamado}', 'LlamadosController@ver')->name('llamados.ver');
        Route::post('llamados', 'LlamadosController@guardar')->name('llamados.guardar');
        Route::get('llamados/{llamado}/editar', 'LlamadosController@editar')->name('llamados.editar');
        Route::get('llamados/{llamado}/editar-tribunal', 'LlamadosController@editarTribunal')->name('llamados.editarTribunal');
        Route::put('llamados/{llamado}', 'LlamadosController@actualizar')->name('llamados.actualizar');
        Route::put('llamados/{llamado}/actualizar-tribunal', 'LlamadosController@actualizarTribunal')->name('llamados.actualizarTribunal');
        Route::delete('llamados/{llamado}', 'LlamadosController@eliminar')->name('llamados.eliminar');
        Route::get('llamados/getLlamadoJson', 'LlamadosController@getLlamadoJson')->name('llamados.getjson');

        //EVALUADORES
        Route::get('evaluadores', 'EvaluadoresController@listado')->name('evaluadores.listado');
        Route::get('evaluadores/{evaluador}', 'EvaluadoresController@ver')->name('evaluadores.ver');
        Route::post('evaluadores', 'EvaluadoresController@guardar')->name('evaluadores.guardar');
        Route::put('evaluadores/{evaluador}', 'EvaluadoresController@actualizar')->name('evaluadores.actualizar');
        Route::delete('evaluadores/{evaluador}', 'EvaluadoresController@eliminar')->name('evaluadores.eliminar');

        // TRIBUNAL
        Route::get('tribunal/crear', 'TribunalesController@crear')->name('tribunales.crear');
        Route::get('tribunal/getCarreras/{id}', 'TribunalesController@getCarreras')->name('tribunales.getCarreras');
        Route::post('tribunal', 'TribunalesController@guardar')->name('tribunales.guardar');

        //POSTULANTES
        Route::get('postulaciones', 'PostulacionesController@listado')->name('postulaciones.listado');
        Route::get('postulaciones/{postulacion}/', 'PostulacionesController@ver')->name('postulaciones.ver');
        Route::get('postulaciones/curriculum/{cv}', 'PostulacionesController@getCv')->name('postulaciones.getCv');
        Route::get('postulaciones/curriculum/{cv}/descargar', 'PostulacionesController@descargarCv')->name('postulaciones.descargarCv');
        Route::get('postulaciones/{postulacion}/asignatura/{asignatura}/evaluar', 'PostulacionesController@evaluar')->name('postulaciones.evaluar');
        Route::put('postulaciones/{asignatura_postulacion}', 'PostulacionesController@guardarPuntaje')->name('postulaciones.guardarPuntaje');
        Route::post('postulaciones/editando/{asignatura_postulacion}/', 'PostulacionesController@editando')->name('postulaciones.editando');


        //INFORMES
        Route::get('informes/{llamado}/pdf', 'InformesController@listado')->name('informes.listado');
        Route::post('informes/{llamado}/pdf', 'InformesController@generarPdf')->name('informes.generarPdf');
        Route::get('informes/{llamado}/xls', 'InformesController@listadoExcel')->name('informes.listadoExcel');
        Route::post('informes/{llamado}/xls', 'InformesController@generarExcel')->name('informes.generarExcel');


        //TABLA
//        Route::get('tabla', 'TablaPonderacionController@listado')->name('tabla.listado');
//        Route::post('tabla', 'TablaPonderacionController@guardar')->name('tabla.guardar');
//        Route::get('/tabla/{tabla}/editar', 'TablaPonderacionController@editar')->name('tabla.editar');
//        Route::put('/tabla/{tabla}', 'TablaPonderacionController@actualizar')->name('tabla.actualizar');
//        Route::delete('/tabla/{tabla}', 'TablaPonderacionController@eliminar')->name('tabla.eliminar');
//        Route::get('/tabla/{tabla}', 'TablaPonderacionController@agregarSubitem')->name('tabla.agregarSubitem');
    });


Auth::routes();

app/Carrera.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Carrera extends Model
{
    protected $table = 'carreras';
    protected $guarded = [];
    // RELACIONES
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function asignaturas()
    {
        return $this->hasMany(Asignatura::class);
    }

    public function evaluadores()
    {
        return $this->belongsToMany(User::class, 'tribunales', 'carrera_id', 'user_id');
    }
    // FIN RELACIONES

    // GETTERS, SETTERS
    public function getEstadoLabelAttribute()
    {
        if ($this->estado){
            return "<span class='badge badge-success'>Activo</span>";
        }
        return "<span class='badge badge-danger'>Deshabilitado</span>";
    }

    // FIN GETTERS, SETTERS

    // SCOPES
    public function scopeBuscarCarrera($query, Request $request)
    {
        if ($request->has('buscar') && !is_null($request->get('buscar'))){
            $query->where('nombre', 'LIKE', "%{$request->get('buscar')}%");
        }
        return $query;
    }
    // FIN SCOPES

    public function estaMateriaAsociada($materia)
    {
        return $this->asignaturas()->where("nombre", $materia)->first();
    }

    public function tribunal()
    {
        return $this->belongsToMany(User::class, 'tribunales', 'carrera_id', 'user_id')->withPivot('llamado_id');
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\ResetPassword;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Authenticatable implements CanResetPassword
{
    use Notifiable, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'username','apellido','email', 'password', 'estado'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tribunales()
    {
        return $this->hasMany(Tribunal::class);
    }

    public function llamados()
    {
        return $this->belongsToMany(Llamado::class,'tribunales');
    }
    //SCOPES
    public function scopeBuscarUsuario($query, Request $request)
    {
        if ($request->has('buscar') && !is_null($request->get('buscar'))){
            $query->where('nombre', 'LIKE', "%{$request->get('buscar')}%")
                ->orWhere('apellido', 'LIKE', "%{$request->get('buscar')}%");
        }
        return $query;
    }

    // FIN SCOPES

    // ACCESOR Y MUTATORS
    public function getFullNameAttribute()
    {
        return "{$this->apellido} {$this->nombre}";
    }

    // FIN ACCESOR Y MUTATORS

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token, $this->email));
    }
}

app/Http/Controllers/Admin/CarrerasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Asignatura;
use App\Carrera;
use App\Http\Requests\CarreraRequest;
use App\Upload;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Silber\Bouncer\BouncerFacade;

class CarrerasController extends Controller
{
    public function listado(Request $request)
    {
        BouncerFacade::authorize('listado-carreras');
        $carreras = Carrera::buscarCarrera($request)
                ->paginate(20);

        return view('admin.carreras.listado', compact('carreras'));
    }

    public function ver(Carrera $carrera)
    {
        BouncerFacade::authorize('ver-carreras');
        $carrera->load('asignaturas');

        return view('admin.carreras.ver', compact('carrera'));
    }

    public function crear()
    {
        BouncerFacade::authorize('crear-carreras');
        $usuarios = User::all();
        return view('admin.carreras.crear', compact('usuarios'));
    }

    public function guardar(CarreraRequest $request)
    {
        BouncerFacade::authorize('guardar-carreras');
        DB::transaction(function () use ($request){
            $carrera = Carrera::create(["nombre"=>$request->get('nombre')]);

            foreach ($request->get('asignatura') as $materia){
                $asignatura = new Asignatura(["nombre"=>$materia]);
                $carrera->asignaturas()->save($asignatura);
            }
        });

        return redirect(route('carreras.crear'))->with('success', "La operación se registro correctamente");
    }

    public function editar(Carrera $carrera)
    {
        BouncerFacade::authorize('editar-carreras');
        $carrera->load('asignaturas');

        return view('admin.carreras.editar', compact('carrera'));
    }

    public function actualizar(Carrera $carrera, CarreraRequest $request)
    {
        BouncerFacade::authorize('actualizar-carreras');
        DB::transaction(function () use ($request, $carrera){

            $carrera->update([
                "nombre" => $request->get('nombre'),
                "estado" => $request->get('estado')
            ]);

            $ids = [];
            foreach ($request->get('asignatura') as $materia){
                Asignatura::find($materia['id'])->update(["nombre" => $materia['nombre']]);
                $ids[] = $materia['id'];
            }

            $carrera->asignaturas()->whereNotIn('id', $ids)->delete();

            if ($request->has('nuevo')){
                foreach ($request->get('nuevo') as  $nuevo){
                    $asignatura = new Asignatura(["nombre"=>$nuevo]);
                    $carrera->asignaturas()->save($asignatura);
                }
            }
        });

        return redirect(route('carreras.listado'))->with('success', "La operación se registro correctamente");
    }

    public function eliminar(Carrera $carrera)
    {
        BouncerFacade::authorize('eliminar-carreras');
        DB::transaction(function () use ($carrera){
            $carrera->delete();
        });

        return redirect(route('carreras.listado'))->with('success', 'La operación se realizo correctamente');
    }
}

resources/views/admin/carreras/crear.blade.php
@extends('layouts.master')
@section('titulo', 'Nueva carrera')
@section('contenido')
    @include('partials.errors')
    @include('partials.success')

    <form action="{{ route('carreras.guardar') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Datos de la carrera</h6>
                    </div>
                    <div class="card-body">

                        <div class="form-group row">
                            <label for="carrera[nombre]">Nombre de la carrera</label>
                            <input type="input" class="form-control" id="nombre" value="{{ old('nombre') }}" required name="nombre" placeholder="Nombre">
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="pb-3 mx-auto">
                <button class="btn btn-primary" id="crear_asignatura">Nueva asignatura</button>
            </div>
        </div>

        <div class="row" id="tarjetero">
            <div class="col-md-3 tarjeta">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Asignatura <span class="numero">1</span></h6>
                        <div class="dropdown no-arrow" style="display: none">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item eliminar">Eliminar</a>
                            </div>
                        </div>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="carrera[nombre]">Nombre de la asignatura</label>
                            <input type="input" class="form-control asignatura_nombre" value="{{ old('asignatura')[1] }}" required name="asignatura[1]" placeholder="Nombre">
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="mx-auto">
                <button class="btn btn-success btn-lg" type="submit">Guardar</button>
            </div>

        </div>
    </form>
    @php
        $asignaturas_old = '';
        if (!is_null(old('asignatura'))){
            $asignaturas_old = old('asignatura');
            unset($asignaturas_old[1]);
        }
    @endphp
@endsection
@section('js')
    <script>
        $(function(){
            $("#crear_asignatura").click(function(e){
                e.preventDefault();
                var cantidad_tarjetas = $(".tarjeta").length;
                var tarjeta = $(".tarjeta:first").clone(true);
                tarjeta.find('.asignatura_nombre')
                    .attr("name", "asignatura["+(++cantidad_tarjetas)+"]")
                    .prop("required", true)
                    .val(null);
                tarjeta.find('.numero')
                    .html(cantidad_tarjetas);
                tarjeta.find('.dropdown')
                    .show();
                $("#tarjetero").append(tarjeta);
            });

            $(document).on("click", ".eliminar", function () {
                $(this).closest(".tarjeta").remove();
            });

            var asignaturas = JSON.parse('<?php echo json_encode($asignaturas_old) ?>');
            if (asignaturas != ''){
                $.each(asignaturas, function (i, item) {
                    var cantidad_tarjetas = $(".tarjeta").length;
                    var tarjeta = $(".tarjeta:first").clone(true);
                    tarjeta.find('.asignatura_nombre')
                        .attr("name", "asignatura["+(++cantidad_tarjetas)+"]")
                        .prop("required", true)
                        .val(item);
                    tarjeta.find('.numero')
                        .html(cantidad_tarjetas);
                    $("#tarjetero").append(tarjeta);
                })
            }

        });
    </script>
@endsection

resources/views/admin/carreras/editar.blade.php
@extends('layouts.master')
@section('titulo', 'Editar carrera')
@section('contenido')
    @include('partials.errors')
    @include('partials.success')

    <form action="{{ route('carreras.actualizar', $carrera) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-9">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Datos de la carrera</h6>
                    </div>
                    <div class="card-body">

                        <div class="form-group row">
                            <label for="nombre">Nombre de la carrera</label>
                            <input type="input" class="form-control" id="nombre" value="{{ $carrera->nombre }}" required name="nombre" placeholder="Nombre">
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Estado de la carrera</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="custom-control custom-switch">
                                <input type="checkbox" @if($carrera->estado) checked @endif class="custom-control-input"
                                       id="estado_checkbox">
                                <label class="custom-control-label" for="estado_checkbox">Estado de la carrera</label>
                                <input type="hidden" id="estado" name="estado" value="{{ $carrera->estado ? 1 : 0 }}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="pb-3 mx-auto">
                <button class="btn btn-primary" id="crear_asignatura">Nueva asignatura</button>
            </div>
        </div>

        <div class="row" id="tarjetero">
        @foreach($carrera->asignaturas as $key => $asignatura)
            <div class="col-md-3 tarjeta">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Asignatura <span class="numero">{{ ($key + 1) }}</span></h6>
                        <div class="dropdown no-arrow" @if($loop->first) style="display: none" @endif>
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item eliminar">Eliminar</a>
                            </div>
                        </div>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="carrera[nombre]">Nombre de la asignatura</label>
                            <input type="input" class="form-control asignatura_nombre" value="{{ $asignatura->nombre  }}" required name="asignatura[{{ ($key+1) }}][nombre]" placeholder="Nombre">
                            <input type="hidden" class="asignatura_id" value="{{ $asignatura->id  }}" required name="asignatura[{{ ($key+1) }}][id]">
                        </div>

                    </div>
                </div>
            </div>
        @endforeach
        </div>

        <div class="row">
            <div class="mx-auto">
                <button class="btn btn-success btn-lg" type="submit">Guardar</button>
            </div>

        </div>
    </form>
    @php
        $asignaturas_old = '';
        if (!is_null(old('asignatura'))){
            $asignaturas_old = old('asignatura');
            unset($asignaturas_old[1]);
        }
    @endphp
@endsection
@section('js')
    <script>
        $(function(){
            $("#crear_asignatura").click(function(e){
                e.preventDefault();
                var cantidad_tarjetas = $(".tarjeta").length;
                var tarjeta = $(".tarjeta:first").clone(true);
                tarjeta.find('.asignatura_nombre')
                    .attr("name", "nuevo["+(++cantidad_tarjetas)+"]")
                    .prop("required", true)
                    .val(null);
                tarjeta.find('.numero')
                    .html(cantidad_tarjetas);
                tarjeta.find('.dropdown')
                    .show();
                $("#tarjetero").append(tarjeta);
            });

            $("#estado_checkbox").change(function () {
               if ($(this).is(":checked")){
                   $("#estado").val(1);
               }else{
                   $("#estado").val(0);
               }
            });

            $(document).on("click", ".eliminar", function () {
                $(this).closest(".tarjeta").remove();
            });

            var asignaturas = JSON.parse('<?php echo json_encode($asignaturas_old) ?>');
            if (asignaturas != ''){
                $.each(asignaturas, function (i, item) {
                    var cantidad_tarjetas = $(".tarjeta").length;
                    var tarjeta = $(".tarjeta:first").clone(true);
                    tarjeta.find('.asignatura_nombre')
                        .attr("name", "nuevo["+(++cantidad_tarjetas)+"]")
                        .prop("required", true)
                        .val(item);
                    tarjeta.find('.numero')
                        .html(cantidad_tarjetas);
                    $("#tarjetero").append(tarjeta);
                })
            }

        });
    </script>
@endsection

resources/views/admin/carreras/listado.blade.php
@extends('layouts.master')
@section('titulo', 'Listado de carreras')
@section('contenido')
    @include('partials.errors')
    @include('partials.success')
    <div class="row" style="margin-bottom: 1%">
        <div class="col">
            <a href="{{ route('carreras.crear') }}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                <span class="text">Nueva carrera</span>
            </a>
        </div>
        <div class="col-md-3">
            <form action="{{ route('carreras.listado') }}" method="GET" id="buscarUsuarioForm">
                <input type="text" class="form-control" value="{{ request('buscar') }}" name="buscar" placeholder="Buscar carrera">
            </form>
        </div>
        <div class="col-md-1">
            <a href="{{ route('carreras.listado') }}" title="Limpiar resultados">
                <i class="fas fa-broom fa-2x"></i>
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead class="thead-dark">
            <th>#</th>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
            @forelse($carreras as $carrera)
                <tr>
                    <td>{{ $carrera->id }}</td>
                    <td>{{ $carrera->nombre }}</td>
                    <td>{!! $carrera->estado_label !!}</td>
                    <td>
                        <a href="{{ route('carreras.ver', $carrera) }}" class="btn btn-primary btn-circle btn-sm" title="Detalle">
                            <i class="fas fa-eye"></i>
                        </a>

                        <a href="{{ route('carreras.editar', $carrera) }}" class="btn btn-warning btn-circle btn-sm editar" title="Editar carrera">
                            <i class="far fa-edit"></i>
                        </a>

                        <span class="btn btn-danger btn-circle btn-sm eliminar cursor" title="Eliminar"
                              data-url="{{route('carreras.eliminar', $carrera->id)}}">
                            <i class="far fa-trash-alt"></i>
                        </span>
                    </td>
                </tr>
            @empty
                <td colspan="5">No se encontraron resultados</td>
            @endforelse
            </tbody>
        </table>

        <div class="modal fade" id="eliminarCarrera" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">¿Desea eliminar la carrera?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <h4><span style="color: red; font-weight: bold">¡ADVERTENCIA!</span> Si elimina la carrera se eliminaran las asignaturas pertenecientes a esta.</h4>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <form method="POST" id="formEliminarCarrera">
                            @csrf
                            {{ method_field('delete') }}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>

        {{ $carreras->appends([
            'buscar' => request('buscar')
        ])->links() }}
    </div>
@endsection
@section('js')
    <script>
        $(function () {
            $(".eliminar").click(function () {
                var url = $(this).data("url");
                $("#formEliminarCarrera").attr("action", url);
                $("#eliminarCarrera").modal('show');
            });
        });
    </script>
@endsection

resources/views/admin/carreras/ver.blade.php
@extends('layouts.master')
@section('titulo', "Detalle de la carrera {$carrera->nombre}"  )
@section('contenido')
<div class="row">

    <div class="col-md-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Asignaturas</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Estado</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($carrera->asignaturas->sortBy('nombre') as $asignatura)
                            <tr>
                                <td>{{ $asignatura->nombre }}</td>
                                <td>{!! $asignatura->estado_label !!}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2">No se encontraron resultados</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Estado</h6>
            </div>
            <div class="card-body mx-auto">
                <h5>{!! $carrera->estado_label !!}</h5>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Evaluadores</h6>
            </div>
            <div class="card-body mx-auto">
                <ul>
                    @forelse($carrera->evaluadores as $evaluador)
                        <li>{{ $evaluador->full_name }}</li>
                    @empty
                        <li>No se encontraron resultados</li>
                    @endforelse
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection